# Generated by Django 4.2.6 on 2023-10-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=28, null=True, verbose_name='名称')),
                ('intro', models.CharField(blank=True, max_length=28, null=True, verbose_name='介绍')),
                ('avatar', models.CharField(blank=True, max_length=300, null=True, verbose_name='头像')),
                ('portrait', models.IntegerField(blank=True, choices=[(1, 'DAO'), (2, 'DEFI'), (3, 'NFT'), (4, '开发者')], null=True, verbose_name='画像')),
                ('quoted_price', models.IntegerField(blank=True, null=True, verbose_name='报价')),
                ('total_reward', models.FloatField(blank=True, null=True, verbose_name='总回报')),
                ('claim_reward', models.FloatField(blank=True, null=True, verbose_name='可领取金额')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=28, null=True, verbose_name='项目名称')),
                ('intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目介绍')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='头像')),
                ('track', models.IntegerField(blank=True, choices=[(1, 'DAO'), (2, 'DEFI'), (3, 'NFT'), (4, 'Tool')], null=True, verbose_name='赛道')),
                ('website', models.URLField(blank=True, max_length=300, null=True, verbose_name='官网')),
                ('twitter', models.CharField(blank=True, max_length=64, null=True, verbose_name='Twitter')),
                ('discord', models.CharField(blank=True, max_length=128, null=True, verbose_name='Discord')),
                ('contract', models.CharField(blank=True, max_length=64, null=True, verbose_name='智能合约')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='任务名')),
                ('platform', models.IntegerField(blank=True, choices=[(1, 'twitter'), (2, 'telegram')], null=True, verbose_name='发布平台')),
                ('area', models.IntegerField(blank=True, choices=[(1, '台湾'), (2, '韩国'), (3, '日本'), (4, '新加坡')], null=True, verbose_name='地区')),
                ('delivery_method', models.IntegerField(blank=True, choices=[(1, '派单'), (2, '先到先得'), (3, '招募')], null=True, verbose_name='结算方式')),
                ('fans_requirement', models.IntegerField(blank=True, null=True, verbose_name='粉丝数量限制')),
                ('requirement', models.CharField(blank=True, max_length=500, null=True, verbose_name='任务要求')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='推广文案')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('people', models.IntegerField(blank=True, default=0, verbose_name='参与人数')),
                ('status', models.IntegerField(blank=True, choices=[(1, '进行中'), (2, '已结束')], default=1, verbose_name='任务状态')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='订单ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='订单金额')),
                ('status', models.IntegerField(blank=True, choices=[(1, '未接单'), (2, '进行中'), (3, '已完成'), (4, '待核验'), (5, '已取消')], null=True, verbose_name='订单状态')),
                ('verify_url', models.URLField(blank=True, null=True, verbose_name='核验URL')),
                ('kol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitgrow_base.kol', verbose_name='KOL')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitgrow_base.task', verbose_name='任务')),
            ],
        ),
    ]
