# Generated by Django 4.2.6 on 2023-10-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitgrow_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kol',
            options={'verbose_name': 'KOL', 'verbose_name_plural': 'KOL'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目方', 'verbose_name_plural': '项目方'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AddField(
            model_name='kol',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='区块链地址'),
        ),
        migrations.AddField(
            model_name='kol',
            name='area',
            field=models.IntegerField(blank=True, choices=[(1, '美国'), (2, '韩国'), (3, '日本'), (4, '东南亚')], null=True, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='kol',
            name='average_display',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='平均展示量'),
        ),
        migrations.AddField(
            model_name='kol',
            name='connectable_user',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='可连接用户'),
        ),
        migrations.AddField(
            model_name='kol',
            name='language',
            field=models.IntegerField(blank=True, choices=[(1, '英语'), (2, '韩语'), (3, '日语'), (4, '其它')], null=True, verbose_name='受众语言'),
        ),
        migrations.AddField(
            model_name='task',
            name='payment_method',
            field=models.IntegerField(blank=True, choices=[(1, '派单'), (2, '先到先得'), (3, '招募')], null=True, verbose_name='结算方式'),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='任务金额'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitgrow_base.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(blank=True, choices=[(1, '发布推文'), (2, '撰写研报')], null=True, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='kol',
            name='avatar',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='task',
            name='delivery_method',
            field=models.IntegerField(blank=True, choices=[(1, '派单'), (2, '先到先得'), (3, '招募')], null=True, verbose_name='派单方式'),
        ),
    ]
