# Generated by Django 4.2.6 on 2023-10-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitgrow_base', '0002_alter_kol_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kol',
            name='language',
            field=models.IntegerField(blank=True, choices=[(1, '英文'), (2, '韩文'), (3, '日文'), (4, '中文')], null=True, verbose_name='受众语言'),
        ),
    ]
